Display URL when lynx failed
Allows for easier removal of invalid URLs.

Signed-off-by: Florian Pritz <bluewind@xinu.at>

diff --git a/w3watch b/w3watch
--- a/w3watch
+++ b/w3watch
@@ -68,6 +68,7 @@ check() {
 		fi
 
 		if [ $? -ne 0 ]; then
+			echo "$url failed" >&2
 			continue
 		fi
 
